# Generated by Django 4.2 on 2023-04-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afro_dtl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_form_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
