# Generated by Django 4.2 on 2023-04-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afro_dtl', '0003_remove_user_form_model_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_form_model',
            name='email',
            field=models.EmailField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='user_form_model',
            name='message',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='user_form_model',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
