# Generated by Django 4.2 on 2023-04-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afro_dtl', '0004_alter_user_form_model_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_form_model',
            name='occupation',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
