# Generated by Django 4.2 on 2023-04-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afro_dtl', '0005_user_form_model_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messenger', models.CharField(blank=True, max_length=100)),
                ('message', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
